name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  # Job_1: PHP Lint
  php-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP 8.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, dom, fileinfo, sqlite3, pdo_sqlite
          coverage: none

      - name: Check PHP Version
        run: php -v

      - name: Run PHP Lint
        run: find . -name "*.php" -not -path "./vendor/*" -exec php -l {} \;

  # Job_2: Laravel Tests
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP 8.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, dom, fileinfo, sqlite3, pdo_sqlite
          coverage: none

      - name: Check PHP Version
        run: php -v

      - name: Check Composer Version
        run: composer -V

      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate App Key
        run: php artisan key:generate

      - name: Run Tests
        run: php artisan test
